# Generated by Django 3.2.4 on 2021-06-17 08:09

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('last_4_digit', models.CharField(max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('call', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.IntegerField(default=0)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkuukApp.client')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkuukApp.store')),
            ],
        ),
        migrations.CreateModel(
            name='Histroy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_type', models.CharField(choices=[('save', '적립'), ('use', '사용')], max_length=5, null=True)),
                ('trade_at', models.DateTimeField(auto_now_add=True)),
                ('before_stamp', models.IntegerField(default=0)),
                ('val_stamp', models.IntegerField(default=0)),
                ('after_stamp', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='kkuukApp.client')),
            ],
        ),
    ]
