# Generated by Django 3.2.3 on 2021-06-07 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('call', models.CharField(max_length=20)),
                ('store_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_4_digit', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='kkuukApp.user')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='kkuukApp.store')),
            ],
        ),
        migrations.CreateModel(
            name='Histroy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_type', models.CharField(choices=[('save', '적립'), ('use', '사용')], max_length=5)),
                ('trade_at', models.DateTimeField(auto_now_add=True)),
                ('before_stamp', models.IntegerField(default=0)),
                ('val_stamp', models.IntegerField(default=0)),
                ('after_stamp', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='kkuukApp.user')),
            ],
        ),
    ]
