# Generated by Django 3.2.4 on 2021-06-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkuukApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='histroy',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='kkuukApp.store'),
            preserve_default=False,
        ),
    ]
