# Generated by Django 3.2.3 on 2021-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkuukApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='pwd',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
