# Generated by Django 3.2.3 on 2021-06-11 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkuukApp', '0002_store_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('last_4_digit', models.CharField(max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_name',
        ),
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='trade_type',
            field=models.CharField(choices=[('save', '적립'), ('use', '사용')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='call',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='pwd',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='kkuukApp.client'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='kkuukApp.client'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
