# Generated by Django 3.2.3 on 2021-06-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkuukApp', '0002_histroy_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='client_name',
            new_name='client',
        ),
    ]
