# Generated by Django 3.2.3 on 2021-06-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkuukApp', '0004_auto_20210611_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histroy',
            old_name='user',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='client',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='seller',
            new_name='store',
        ),
    ]
